/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.warehouse;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    public Manager() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }
    public Manager(String uname) {
        Manager.setText(uname);
        initComponents();
        
        //Jframe Center code
       Toolkit toolkit=getToolkit();
        Dimension size=toolkit.getScreenSize();
        setLocation(size.width/2 -getWidth()/2, size.height/2-getHeight()/2);
        

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        move = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        register = new javax.swing.JButton();
        addStorage = new javax.swing.JButton();
        closestorge = new javax.swing.JButton();
        createoper = new javax.swing.JButton();
        Monthlyreport = new javax.swing.JButton();
        calculte = new javax.swing.JButton();
        Manager = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        move.setBackground(new java.awt.Color(255, 255, 255));
        move.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        move.setPreferredSize(new java.awt.Dimension(730, 521));
        move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moveMouseDragged(evt);
            }
        });
        move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moveMousePressed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        delete.setText("Delet User");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(255, 255, 255));
        register.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        register.setText("Register User");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        addStorage.setBackground(new java.awt.Color(255, 255, 255));
        addStorage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addStorage.setText("Add New Storage Job");
        addStorage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStorageActionPerformed(evt);
            }
        });

        closestorge.setBackground(new java.awt.Color(255, 255, 255));
        closestorge.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        closestorge.setText("Close Existing Storage Job");
        closestorge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closestorgeActionPerformed(evt);
            }
        });

        createoper.setBackground(new java.awt.Color(255, 255, 255));
        createoper.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createoper.setText("Create Operator Accounts");
        createoper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createoperActionPerformed(evt);
            }
        });

        Monthlyreport.setBackground(new java.awt.Color(255, 255, 255));
        Monthlyreport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Monthlyreport.setText("Calculate Monthly Reports");
        Monthlyreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthlyreportActionPerformed(evt);
            }
        });

        calculte.setBackground(new java.awt.Color(255, 255, 255));
        calculte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculte.setText("Calculate The Bill For Storage Job");
        calculte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculteActionPerformed(evt);
            }
        });

        Manager.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Manager.setText("WELCOME MANAGER");

        logout.setBackground(new java.awt.Color(255, 255, 255));
        logout.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Downloads\\bms\\close Jframe.png")); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("Z:\\SCREENSHOT\\UI iImge\\manager.png")); // NOI18N

        javax.swing.GroupLayout moveLayout = new javax.swing.GroupLayout(move);
        move.setLayout(moveLayout);
        moveLayout.setHorizontalGroup(
            moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Manager)
                .addGap(134, 134, 134)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSeparator1)
            .addGroup(moveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moveLayout.createSequentialGroup()
                        .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(register, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(addStorage)
                            .addComponent(closestorge, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createoper, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(calculte)
                            .addComponent(Monthlyreport, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moveLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moveLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(moveLayout.createSequentialGroup()
                        .addComponent(logout)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        moveLayout.setVerticalGroup(
            moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moveLayout.createSequentialGroup()
                .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(moveLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Manager))
                    .addComponent(jButton8))
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(moveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(moveLayout.createSequentialGroup()
                        .addComponent(register)
                        .addGap(31, 31, 31)
                        .addComponent(delete)
                        .addGap(30, 30, 30)
                        .addComponent(addStorage)
                        .addGap(34, 34, 34)
                        .addComponent(closestorge)
                        .addGap(37, 37, 37)
                        .addComponent(createoper)
                        .addGap(40, 40, 40)
                        .addComponent(calculte)
                        .addGap(40, 40, 40)
                        .addComponent(Monthlyreport))
                    .addGroup(moveLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(logout)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(move, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        RegisterUser Regi= new RegisterUser();
        Regi.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_registerActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
       DeleteUser delete=new DeleteUser();
       delete.setVisible(true);
       this.setVisible(false);
       
      
    }//GEN-LAST:event_deleteActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
    JFrame frame= new JFrame("EXIT"); 
          if(JOptionPane.showConfirmDialog(frame,"IF YOU WANT LOGOUT","LOGOUT",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
          {
              MainLogin logout=new MainLogin();
              logout.setVisible(true);
              this.setVisible(false);
          } 
    }//GEN-LAST:event_logoutActionPerformed

    private void addStorageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStorageActionPerformed
        // TODO add your handling code here:
        AddStorage add1=new AddStorage();
        add1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addStorageActionPerformed

    private void createoperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createoperActionPerformed
        // TODO add your handling code here:
        CreateOperators CO=new CreateOperators();
        CO.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_createoperActionPerformed

    private void calculteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculteActionPerformed
        
        CalculateTheBill cal=new CalculateTheBill();
        cal.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_calculteActionPerformed

    private void MonthlyreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthlyreportActionPerformed
        
        MonthlyReport rep=new MonthlyReport();
        rep.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_MonthlyreportActionPerformed

    private void closestorgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closestorgeActionPerformed
        CloseExitStorageJob close=new CloseExitStorageJob();
        close.setVisible(true);
        this.setVisible(false);
                
        
        
        
    }//GEN-LAST:event_closestorgeActionPerformed
private int xMouse,yMouse;
    private void moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMousePressed
      xMouse=evt.getX();
      yMouse=evt.getY();
    }//GEN-LAST:event_moveMousePressed

    private void moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveMouseDragged
      int x=evt.getXOnScreen();
      int y=evt.getYOnScreen();
      setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_moveMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new Manager().setVisible(true);
           }
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Manager;
    private javax.swing.JButton Monthlyreport;
    private javax.swing.JButton addStorage;
    private javax.swing.JButton calculte;
    private javax.swing.JButton closestorge;
    private javax.swing.JButton createoper;
    private javax.swing.JButton delete;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JPanel move;
    private javax.swing.JButton register;
    // End of variables declaration//GEN-END:variables
}
